name: CI

on:
  push:
    branches: [ pyinstaller-switch-workflow-test ]

jobs:
  build-linux:
    runs-on: ubuntu-18.04

    steps:
    - name: Install dependencies
      run: sudo apt-get install libglib2.0-dev libegl1-mesa-dev libfreetype6-dev libx11-dev libx11-xcb-dev libxext-dev libxi-dev libxrender-dev libxcb1-dev libxcb-util-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxkbcommon-x11-dev libxkbcommon-dev libxcb-xinerama0-dev libusb-1.0-0-dev libudev-dev

    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7.x'

    - name: Setup venv
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade setuptools
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build
      run: |
        source venv/bin/activate
        pyinstaller sonix-flasher.spec
        cd dist
        tar cfJ flasher-linux.tar.xz "sonix-flasher"

    - uses: actions/upload-artifact@v1
      with:
        name: flasher-linux
        path: dist/flasher-linux.tar.xz

  build-mac:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7.x'

    - name: Setup venv
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install cython
        pip install -r requirements.txt

    - name: Build
      run: |
        source venv/bin/activate
        pyinstaller sonix-flasher.spec
        hdiutil create -volname "sonix-flasher" -srcfolder "dist/sonix-flasher/sonix-flasher.app" -ov -format UDZO flasher-mac.dmg

    - uses: actions/upload-artifact@v1
      with:
        name: flasher-mac
        path: flasher-mac.dmg

  build-win:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7.x'

    - name: Setup venv
      run: |
        python -m venv venv
        . .\venv\Scripts\activate.ps1
        pip install -r requirements.txt

    - name: Build
      run: |
        . .\venv\Scripts\activate.ps1
        pyinstaller sonix-flasher.spec
        Compress-Archive -Path "dist\sonix-flasher" -DestinationPath flasher-win.zip

    - uses: actions/upload-artifact@v1
      with:
        name: flasher-win
        path: flasher-win.zip
