name: CI

on:
  push:
    branches: [ pyinstaller-switch-workflow-test ]

jobs:
  build-linux:
    runs-on: ubuntu-18.04

    steps:
    - name: Install dependencies
      run: sudo apt-get install qtbase5-dev libxcomposite-dev libxkbcommon-x11-dev libglib2.0-dev libusb-1.0-0-dev libudev-dev

    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7.x'

    - name: Setup venv
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade setuptools
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build
      run: |
        source venv/bin/activate
        pyinstaller sonix-flasher.spec
        cd dist
        tar cfJ flasher-linux.tar.xz "sonix-flasher"

    - uses: actions/upload-artifact@v1
      with:
        name: flasher-linux
        path: dist/flasher-linux.tar.xz

  build-mac:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7.x'

    - name: Setup venv
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install cython
        pip install -r requirements.txt

    - name: Build
      run: |
        source venv/bin/activate
        pyinstaller --onefile -n "sonix-flasher" --windowed src/sonix-flasher/main.py
        hdiutil create -volname "sonix-flasher" -srcfolder "dist/" -ov -format UDZO flasher-mac.dmg

    - uses: actions/upload-artifact@v1
      with:
        name: flasher-mac
        path: flasher-mac.dmg

  build-win:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7.x'

    - name: Setup venv
      run: |
        python -m venv venv
        . .\venv\Scripts\activate.ps1
        pip install -r requirements.txt

    - name: Build
      run: |
        . .\venv\Scripts\activate.ps1
        pyinstaller sonix-flasher.spec
        Compress-Archive -Path "dist\sonix-flasher" -DestinationPath flasher-win.zip

    - uses: actions/upload-artifact@v1
      with:
        name: flasher-win
        path: flasher-win.zip
